version: '2'
services:
    realylast-app:
        image: realylast
        external_links:
            - realylast-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=realylast
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    realylast-mongodb:
        extends:
            file: mongodb.yml
            service: realylast-mongodb
