version: '2'
services:
    realylast-mongodb:
        container_name: realylast-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        command: mongos --configdb realylast-mongodb-config
    realylast-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    realylast-mongodb-config:
        image: mongo:3.2.10
        container_name: realylast-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
